// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzMFOgbFUmcSBpQQb5nW2WdZhPC18LX5c',
    appId: '1:352249299975:web:a416bd8f3282eb6c4796a2',
    messagingSenderId: '352249299975',
    projectId: 'test-7643a',
    authDomain: 'test-7643a.firebaseapp.com',
    storageBucket: 'test-7643a.appspot.com',
    measurementId: 'G-H8WHZJ6447',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAWeTYXA4xQVd_IU9Xpb7HLgkwnYwg3WU',
    appId: '1:352249299975:android:a27600ec3856f9244796a2',
    messagingSenderId: '352249299975',
    projectId: 'test-7643a',
    storageBucket: 'test-7643a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlLWe_UxWUs8JUUABhCNZR9DitpCn1ipc',
    appId: '1:352249299975:ios:e49e05e4bcae45554796a2',
    messagingSenderId: '352249299975',
    projectId: 'test-7643a',
    storageBucket: 'test-7643a.appspot.com',
    iosBundleId: 'com.example.fire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlLWe_UxWUs8JUUABhCNZR9DitpCn1ipc',
    appId: '1:352249299975:ios:1179259477b5fe2c4796a2',
    messagingSenderId: '352249299975',
    projectId: 'test-7643a',
    storageBucket: 'test-7643a.appspot.com',
    iosBundleId: 'com.example.fire.RunnerTests',
  );
}
